// GENERATED FILE — do not edit manually.
// Regenerated by `bun run scripts/sync.ts` from registry/ui/registry.json.

export type RegistryItemFile = {
  path: string
  type: string
  target: string
}

export type RegistryItem = {
  name: string
  type: string
  title: string
  description: string
  dependencies?: string[]
  registryDependencies?: string[]
  files: RegistryItemFile[]
}

export const registryItems: RegistryItem[] = [
  {
    "name": "spinner",
    "type": "registry:ui",
    "title": "Spinner",
    "description": "A lightweight loading spinner with no runtime dependencies.",
    "files": [
      {
        "path": "spinner.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/spinner.tsx"
      }
    ]
  },
  {
    "name": "sidebar",
    "type": "registry:ui",
    "title": "Sidebar",
    "description": "A collapsible sidebar that persists its state in localStorage.",
    "registryDependencies": [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
      "use-mobile"
    ],
    "files": [
      {
        "path": "navigation/sidebar.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/sidebar.tsx"
      }
    ]
  },
  {
    "name": "app-sidebar",
    "type": "registry:ui",
    "title": "App Sidebar",
    "description": "A config-driven application sidebar with main navigation, projects, secondary links, and a user menu.",
    "registryDependencies": [
      "@hoogin/sidebar",
      "avatar",
      "collapsible",
      "dropdown-menu"
    ],
    "files": [
      {
        "path": "navigation/app-sidebar.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/app-sidebar.tsx"
      },
      {
        "path": "navigation/nav-main.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/nav-main.tsx"
      },
      {
        "path": "navigation/nav-projects.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/nav-projects.tsx"
      },
      {
        "path": "navigation/nav-secondary.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/nav-secondary.tsx"
      },
      {
        "path": "navigation/nav-user.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/navigation/nav-user.tsx"
      },
      {
        "path": "navigation/sidebar.types.ts",
        "type": "registry:file",
        "target": "hoogin/ui/navigation/sidebar.types.ts"
      }
    ]
  },
  {
    "name": "auth-provider",
    "type": "registry:ui",
    "title": "Auth Provider",
    "description": "An authentication provider for TrailBase with persisted sessions and sign in, sign up, and sign out helpers.",
    "dependencies": [
      "trailbase"
    ],
    "files": [
      {
        "path": "auth/auth-provider.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/auth/auth-provider.tsx"
      }
    ]
  },
  {
    "name": "theme-provider",
    "type": "registry:ui",
    "title": "Theme Provider",
    "description": "A theme provider with system detection, storage sync, and a keyboard shortcut.",
    "files": [
      {
        "path": "theme/theme-provider.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/theme/theme-provider.tsx"
      }
    ]
  },
  {
    "name": "theme-toggle",
    "type": "registry:ui",
    "title": "Theme Toggle",
    "description": "A dark/light mode toggle button that uses the theme provider.",
    "registryDependencies": [
      "button",
      "@hoogin/theme-provider"
    ],
    "files": [
      {
        "path": "theme/theme-toggle.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/theme/theme-toggle.tsx"
      }
    ]
  },
  {
    "name": "data-table",
    "type": "registry:ui",
    "title": "Data Table",
    "description": "A sortable, paginated, selectable data table built on TanStack Table.",
    "dependencies": [
      "@tanstack/react-table",
      "lucide-react"
    ],
    "registryDependencies": [
      "@hoogin/data-table-cells",
      "@hoogin/data-table-view-options",
      "@hoogin/data-table-faceted-filter",
      "table",
      "button",
      "select",
      "checkbox",
      "dropdown-menu",
      "input"
    ],
    "files": [
      {
        "path": "data-table/data-table.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/data-table.tsx"
      },
      {
        "path": "data-table/data-table-pagination.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/data-table-pagination.tsx"
      },
      {
        "path": "data-table/data-table.types.ts",
        "type": "registry:file",
        "target": "hoogin/ui/data-table/data-table.types.ts"
      },
      {
        "path": "data-table/data-table-toolbar.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/data-table-toolbar.tsx"
      }
    ]
  },
  {
    "name": "data-table-cells",
    "type": "registry:ui",
    "title": "Data Table Cells",
    "description": "Cell components for displaying typed values (text, email, date, currency) in data tables.",
    "dependencies": [
      "lucide-react"
    ],
    "registryDependencies": [
      "badge",
      "button",
      "dropdown-menu"
    ],
    "files": [
      {
        "path": "data-table/cells/formatted.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/formatted.cell.tsx"
      },
      {
        "path": "data-table/cells/text.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/text.cell.tsx"
      },
      {
        "path": "data-table/cells/email.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/email.cell.tsx"
      },
      {
        "path": "data-table/cells/date.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/date.cell.tsx"
      },
      {
        "path": "data-table/cells/currency.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/currency.cell.tsx"
      },
      {
        "path": "data-table/cells/checkbox.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/checkbox.cell.tsx"
      },
      {
        "path": "data-table/cells/badge.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/badge.cell.tsx"
      },
      {
        "path": "data-table/cells/action.cell.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/cells/action.cell.tsx"
      },
      {
        "path": "data-table/cells/formatters.utils.tsx",
        "type": "registry:file",
        "target": "hoogin/ui/data-table/cells/formatters.utils.tsx"
      }
    ]
  },
  {
    "name": "data-table-view-options",
    "type": "registry:ui",
    "title": "Data Table View Options",
    "description": "A dropdown menu to toggle column visibility for a data table.",
    "dependencies": [
      "@tanstack/react-table",
      "lucide-react"
    ],
    "registryDependencies": [
      "button",
      "dropdown-menu"
    ],
    "files": [
      {
        "path": "data-table/data-table-view-options.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/data-table-view-options.tsx"
      }
    ]
  },
  {
    "name": "data-table-faceted-filter",
    "type": "registry:ui",
    "title": "Data Table Faceted Filter",
    "description": "A faceted filter for data tables with searchable options, checkbox multi-select, and a clear action.",
    "dependencies": [
      "lucide-react"
    ],
    "registryDependencies": [
      "badge",
      "button",
      "checkbox",
      "command",
      "popover",
      "separator"
    ],
    "files": [
      {
        "path": "data-table/data-table-faceted-filter.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/data-table/data-table-faceted-filter.tsx"
      }
    ]
  },
  {
    "name": "form-fields",
    "type": "registry:ui",
    "title": "Form Fields",
    "description": "Form layout and field components for TanStack Form with zod validation.",
    "dependencies": [
      "@tanstack/react-form",
      "date-fns",
      "lucide-react",
      "react-day-picker"
    ],
    "registryDependencies": [
      "input",
      "input-group",
      "checkbox",
      "select",
      "textarea",
      "button",
      "calendar",
      "popover"
    ],
    "files": [
      {
        "path": "forms/form.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form.tsx"
      },
      {
        "path": "forms/form.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form.field.tsx"
      },
      {
        "path": "forms/form.utils.ts",
        "type": "registry:file",
        "target": "hoogin/ui/forms/form.utils.ts"
      },
      {
        "path": "data-table/cells/formatters.utils.tsx",
        "type": "registry:file",
        "target": "hoogin/ui/data-table/cells/formatters.utils.tsx"
      },
      {
        "path": "forms/form-text.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-text.field.tsx"
      },
      {
        "path": "forms/form-email.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-email.field.tsx"
      },
      {
        "path": "forms/form-number.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-number.field.tsx"
      },
      {
        "path": "forms/form-currency.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-currency.field.tsx"
      },
      {
        "path": "forms/form-date.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-date.field.tsx"
      },
      {
        "path": "forms/form-time.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-time.field.tsx"
      },
      {
        "path": "forms/form-password.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-password.field.tsx"
      },
      {
        "path": "forms/form-checkbox.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-checkbox.field.tsx"
      },
      {
        "path": "forms/form-select.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-select.field.tsx"
      },
      {
        "path": "forms/form-textarea.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-textarea.field.tsx"
      },
      {
        "path": "forms/form-strong-password.field.tsx",
        "type": "registry:ui",
        "target": "hoogin/ui/forms/form-strong-password.field.tsx"
      }
    ]
  },
  {
    "name": "sidebar-layout",
    "type": "registry:block",
    "title": "Sidebar Layout",
    "description": "A full application layout with a collapsible sidebar, header, and content area.",
    "registryDependencies": [
      "@hoogin/sidebar",
      "@hoogin/app-sidebar",
      "@hoogin/theme-toggle",
      "separator",
      "tooltip"
    ],
    "files": [
      {
        "path": "blocks/sidebar-layout.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/sidebar-layout/sidebar-layout.tsx"
      }
    ]
  },
  {
    "name": "admin-page",
    "type": "registry:block",
    "title": "Admin Page",
    "description": "A generic CRUD admin page built on the data table with a sheet-based create, detail, edit, and delete workflow.",
    "dependencies": [
      "zod"
    ],
    "registryDependencies": [
      "@hoogin/data-table",
      "@hoogin/data-table-cells",
      "sheet",
      "button"
    ],
    "files": [
      {
        "path": "blocks/admin-page.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/admin-page/admin-page.tsx"
      }
    ]
  },
  {
    "name": "signup-page",
    "type": "registry:block",
    "title": "Signup Page",
    "description": "A centered signup page with a logo, card, and a TanStack Form powered signup form with a strong password field.",
    "dependencies": [
      "zod"
    ],
    "registryDependencies": [
      "@hoogin/form-fields",
      "card",
      "button"
    ],
    "files": [
      {
        "path": "blocks/signup-page.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/signup-page/signup-page.tsx"
      },
      {
        "path": "blocks/signup-form.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/signup-page/signup-form.tsx"
      }
    ]
  },
  {
    "name": "signin-page",
    "type": "registry:block",
    "title": "Signin Page",
    "description": "A centered signin page with a logo, card, and a TanStack Form powered signin form.",
    "dependencies": [
      "zod"
    ],
    "registryDependencies": [
      "@hoogin/form-fields",
      "card",
      "button"
    ],
    "files": [
      {
        "path": "blocks/signin-page.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/signin-page/signin-page.tsx"
      },
      {
        "path": "blocks/signin-form.tsx",
        "type": "registry:block",
        "target": "hoogin/blocks/signin-page/signin-form.tsx"
      }
    ]
  }
]

export function getRegistryItem(name: string): RegistryItem | undefined {
  return registryItems.find((item) => item.name === name)
}
