import { copyFile, mkdir, readFile, readdir, writeFile } from "node:fs/promises"
import { watch } from "node:fs"
import { dirname, join } from "node:path"

const root = join(import.meta.dir, "..")
const registryDir = join(root, "registry", "ui")
const registryJson = join(registryDir, "registry.json")
const exampleSrc = join(root, "example", "src")
const hooginDir = join(exampleSrc, "hoogin")

const watchMode = process.argv.includes("--watch")
const reverse = process.argv.includes("--reverse")

type RegistryFile = { path: string; target: string }
type RegistryItem = { name: string; files?: RegistryFile[] }

async function loadFiles(): Promise<RegistryFile[]> {
  const raw = JSON.parse(await readFile(registryJson, "utf8"))
  return (raw.items ?? []).flatMap((item: RegistryItem) => item.files ?? [])
}

// example path derives from the install target: hoogin/... → example/src/hoogin/...
// registry path is the declared payload path relative to registry/ui/.
function pairFor(file: RegistryFile) {
  return {
    name: file.path,
    example: join(exampleSrc, file.target),
    registry: join(registryDir, file.path),
  }
}

async function syncPair(pair: { name: string; from: string; to: string }) {
  await mkdir(dirname(pair.to), { recursive: true })
  await copyFile(pair.from, pair.to)
  console.log(`synced ${pair.name}`)
}

async function generateRegistryConfig() {
  const raw = JSON.parse(await readFile(registryJson, "utf8"))
  const lines = [
    "// GENERATED FILE — do not edit manually.",
    "// Regenerated by `bun run scripts/sync.ts` from registry/ui/registry.json.",
    "",
    "export type RegistryItemFile = {",
    "  path: string",
    "  type: string",
    "  target: string",
    "}",
    "",
    "export type RegistryItem = {",
    "  name: string",
    "  type: string",
    "  title: string",
    "  description: string",
    "  dependencies?: string[]",
    "  registryDependencies?: string[]",
    "  files: RegistryItemFile[]",
    "}",
    "",
    `export const registryItems: RegistryItem[] = ${JSON.stringify(raw.items ?? [], null, 2)}`,
    "",
    "export function getRegistryItem(name: string): RegistryItem | undefined {",
    "  return registryItems.find((item) => item.name === name)",
    "}",
  ]
  const target = join(exampleSrc, "config", "registry.ts")
  await writeFile(target, lines.join("\n") + "\n")
  console.log("generated example/src/config/registry.ts")
}

async function warnUnregistered() {
  const files = await loadFiles()
  const registered = new Set(files.map((f) => join(exampleSrc, f.target)))
  async function walk(dir: string): Promise<string[]> {
    const out: string[] = []
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const p = join(dir, entry.name)
      if (entry.isDirectory()) out.push(...(await walk(p)))
      else out.push(p)
    }
    return out
  }
  for (const file of await walk(join(hooginDir, "ui"))) {
    if (!registered.has(file) && !file.endsWith("registry.json")) {
      console.log(`  ! ${file} is not registered in registry/ui/registry.json`)
    }
  }
}

async function syncAll() {
  const files = await loadFiles()
  for (const file of files) {
    const pair = pairFor(file)
    await syncPair(
      reverse
        ? { name: pair.name, from: pair.registry, to: pair.example }
        : { name: pair.name, from: pair.example, to: pair.registry }
    )
  }
  if (!reverse) await warnUnregistered()
  await generateRegistryConfig()
  console.log(`Synced ${files.length} file(s) (${reverse ? "registry → example" : "example → registry"}).`)
}

if (watchMode) {
  await syncAll()
  let timer: ReturnType<typeof setTimeout> | undefined
  // ponytail: debounced full re-sync on any change under the watched tree —
  // ~50 file copies, cheap; per-file watchers not worth the complexity.
  const source = reverse ? registryDir : hooginDir
  console.log(`Watching ${source} for changes...`)
  watch(source, { recursive: true }, () => {
    clearTimeout(timer)
    timer = setTimeout(() => syncAll().catch((err) => console.error(err)), 100)
  })
} else {
  await syncAll()
}
