import { copyFile, readFile, readdir, writeFile } from "node:fs/promises"
import { watch } from "node:fs"
import { join } from "node:path"

const root = join(import.meta.dir, "..")
const sourceDir = join(root, "example", "src", "hoogin", "ui")
const targetDir = join(root, "registry", "ui")
const blockSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "sidebar-layout",
  "sidebar-layout.tsx"
)
const blockTarget = join(root, "registry", "ui", "sidebar-layout.tsx")
const adminPageSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "admin-page",
  "admin-page.tsx"
)
const adminPageTarget = join(root, "registry", "ui", "admin-page.tsx")
const signupPageSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "signup-page",
  "signup-page.tsx"
)
const signupPageTarget = join(root, "registry", "ui", "signup-page.tsx")
const signupFormSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "signup-page",
  "signup-form.tsx"
)
const signupFormTarget = join(root, "registry", "ui", "signup-form.tsx")
const signinPageSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "signin-page",
  "signin-page.tsx"
)
const signinPageTarget = join(root, "registry", "ui", "signin-page.tsx")
const signinFormSource = join(
  root,
  "example",
  "src",
  "hoogin",
  "blocks",
  "signin-page",
  "signin-form.tsx"
)
const signinFormTarget = join(root, "registry", "ui", "signin-form.tsx")

const watchMode = process.argv.includes("--watch")
const reverse = process.argv.includes("--reverse")

const [from, to, label] = reverse
  ? [targetDir, sourceDir, "registry → example"]
  : [sourceDir, targetDir, "example → registry"]

const fileMappings = [
  {
    from: reverse ? blockTarget : blockSource,
    to: reverse ? blockSource : blockTarget,
    name: "sidebar-layout.tsx",
  },
  {
    from: reverse ? adminPageTarget : adminPageSource,
    to: reverse ? adminPageSource : adminPageTarget,
    name: "admin-page.tsx",
  },
  {
    from: reverse ? signupPageTarget : signupPageSource,
    to: reverse ? signupPageSource : signupPageTarget,
    name: "signup-page.tsx",
  },
  {
    from: reverse ? signupFormTarget : signupFormSource,
    to: reverse ? signupFormSource : signupFormTarget,
    name: "signup-form.tsx",
  },
  {
    from: reverse ? signinPageTarget : signinPageSource,
    to: reverse ? signinPageSource : signinPageTarget,
    name: "signin-page.tsx",
  },
  {
    from: reverse ? signinFormTarget : signinFormSource,
    to: reverse ? signinFormSource : signinFormTarget,
    name: "signin-form.tsx",
  },
]

async function registeredItems(): Promise<Set<string>> {
  const raw = JSON.parse(
    await readFile(join(root, "registry", "ui", "registry.json"), "utf8")
  )
  const names = new Set<string>()
  for (const item of raw.items ?? []) {
    names.add(item.name)
    for (const file of item.files ?? []) {
      names.add(file.path.replace(/\.(ts|tsx)$/, ""))
    }
  }
  return names
}

async function syncOne(file: string) {
  await copyFile(join(from, file), join(to, file))
  console.log(`synced ${file}`)
}

async function syncFileMapping(mapping: (typeof fileMappings)[number]) {
  await copyFile(mapping.from, mapping.to)
  console.log(`synced ${mapping.name}`)
}

async function generateRegistryConfig() {
  const raw = JSON.parse(
    await readFile(join(root, "registry", "ui", "registry.json"), "utf8")
  )
  const items = raw.items ?? []
  const lines = [
    "// GENERATED FILE — do not edit manually.",
    "// Regenerated by `bun run scripts/sync.ts` from registry/ui/registry.json.",
    "",
    "export type RegistryItemFile = {",
    "  path: string",
    "  type: string",
    "  target: string",
    "}",
    "",
    "export type RegistryItem = {",
    "  name: string",
    "  type: string",
    "  title: string",
    "  description: string",
    "  dependencies?: string[]",
    "  registryDependencies?: string[]",
    "  files: RegistryItemFile[]",
    "}",
    "",
    `export const registryItems: RegistryItem[] = ${JSON.stringify(items, null, 2)}`,
    "",
    "export function getRegistryItem(name: string): RegistryItem | undefined {",
    "  return registryItems.find((item) => item.name === name)",
    "}",
  ]
  const target = join(root, "example", "src", "config", "registry.ts")
  await writeFile(target, lines.join("\n") + "\n")
  console.log("generated example/src/config/registry.ts")
}

async function syncAll() {
  const items = await registeredItems()
  const files = (await readdir(from)).filter(
    (file) => !file.endsWith("registry.json") && !file.startsWith(".")
  )
  for (const file of files) {
    await syncOne(file)
    if (!reverse) {
      const name = file.replace(/\.(ts|tsx)$/, "")
      if (!items.has(name)) {
        console.log(`  ! ${file} is not registered in registry/ui/registry.json`)
      }
    }
  }
  for (const mapping of fileMappings) {
    await syncFileMapping(mapping)
  }
  await generateRegistryConfig()
  console.log(
    `Synced ${files.length + fileMappings.length} file(s) (${label}).`
  )
}

if (watchMode) {
  await syncAll()
  console.log(`Watching ${from} for changes...`)
  watch(from, (_event, filename) => {
    if (typeof filename !== "string") return
    if (filename.endsWith("registry.json")) return
    syncOne(filename).catch((err) => console.error(err))
  })
} else {
  await syncAll()
}
