/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsIntroductionRouteImport } from './routes/docs/introduction'
import { Route as DocsBlocksAdminPageRouteImport } from './routes/docs/blocks/admin-page'
import { Route as DocsBlocksSidebarLayoutRouteImport } from './routes/docs/blocks/sidebar-layout'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs/components/index'
import { Route as DocsComponentsAppSidebarRouteImport } from './routes/docs/components/app-sidebar'
import { Route as DocsComponentsDataTableRouteImport } from './routes/docs/components/data-table'
import { Route as DocsComponentsDataTableCellsRouteImport } from './routes/docs/components/data-table-cells'
import { Route as DocsComponentsDataTableViewOptionsRouteImport } from './routes/docs/components/data-table-view-options'
import { Route as DocsComponentsFormCheckboxFieldRouteImport } from './routes/docs/components/form-checkbox-field'
import { Route as DocsComponentsFormCurrencyFieldRouteImport } from './routes/docs/components/form-currency-field'
import { Route as DocsComponentsFormDateFieldRouteImport } from './routes/docs/components/form-date-field'
import { Route as DocsComponentsFormEmailFieldRouteImport } from './routes/docs/components/form-email-field'
import { Route as DocsComponentsFormFieldsRouteImport } from './routes/docs/components/form-fields'
import { Route as DocsComponentsFormNumberFieldRouteImport } from './routes/docs/components/form-number-field'
import { Route as DocsComponentsFormPasswordFieldRouteImport } from './routes/docs/components/form-password-field'
import { Route as DocsComponentsFormSelectFieldRouteImport } from './routes/docs/components/form-select-field'
import { Route as DocsComponentsFormStrongPasswordFieldRouteImport } from './routes/docs/components/form-strong-password-field'
import { Route as DocsComponentsFormTextFieldRouteImport } from './routes/docs/components/form-text-field'
import { Route as DocsComponentsFormTextareaFieldRouteImport } from './routes/docs/components/form-textarea-field'
import { Route as DocsComponentsFormTimeFieldRouteImport } from './routes/docs/components/form-time-field'
import { Route as DocsComponentsSidebarRouteImport } from './routes/docs/components/sidebar'
import { Route as DocsComponentsSpinnerRouteImport } from './routes/docs/components/spinner'
import { Route as DocsComponentsThemeProviderRouteImport } from './routes/docs/components/theme-provider'
import { Route as DocsComponentsThemeToggleRouteImport } from './routes/docs/components/theme-toggle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntroductionRoute = DocsIntroductionRouteImport.update({
  id: '/docs/introduction',
  path: '/docs/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBlocksAdminPageRoute = DocsBlocksAdminPageRouteImport.update({
  id: '/docs/blocks/admin-page',
  path: '/docs/blocks/admin-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBlocksSidebarLayoutRoute = DocsBlocksSidebarLayoutRouteImport.update({
  id: '/docs/blocks/sidebar-layout',
  path: '/docs/blocks/sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/docs/components/',
  path: '/docs/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsAppSidebarRoute =
  DocsComponentsAppSidebarRouteImport.update({
    id: '/docs/components/app-sidebar',
    path: '/docs/components/app-sidebar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsDataTableRoute = DocsComponentsDataTableRouteImport.update({
  id: '/docs/components/data-table',
  path: '/docs/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsDataTableCellsRoute =
  DocsComponentsDataTableCellsRouteImport.update({
    id: '/docs/components/data-table-cells',
    path: '/docs/components/data-table-cells',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsDataTableViewOptionsRoute =
  DocsComponentsDataTableViewOptionsRouteImport.update({
    id: '/docs/components/data-table-view-options',
    path: '/docs/components/data-table-view-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormCheckboxFieldRoute =
  DocsComponentsFormCheckboxFieldRouteImport.update({
    id: '/docs/components/form-checkbox-field',
    path: '/docs/components/form-checkbox-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormCurrencyFieldRoute =
  DocsComponentsFormCurrencyFieldRouteImport.update({
    id: '/docs/components/form-currency-field',
    path: '/docs/components/form-currency-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormDateFieldRoute =
  DocsComponentsFormDateFieldRouteImport.update({
    id: '/docs/components/form-date-field',
    path: '/docs/components/form-date-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormEmailFieldRoute =
  DocsComponentsFormEmailFieldRouteImport.update({
    id: '/docs/components/form-email-field',
    path: '/docs/components/form-email-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormFieldsRoute =
  DocsComponentsFormFieldsRouteImport.update({
    id: '/docs/components/form-fields',
    path: '/docs/components/form-fields',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormNumberFieldRoute =
  DocsComponentsFormNumberFieldRouteImport.update({
    id: '/docs/components/form-number-field',
    path: '/docs/components/form-number-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormPasswordFieldRoute =
  DocsComponentsFormPasswordFieldRouteImport.update({
    id: '/docs/components/form-password-field',
    path: '/docs/components/form-password-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormSelectFieldRoute =
  DocsComponentsFormSelectFieldRouteImport.update({
    id: '/docs/components/form-select-field',
    path: '/docs/components/form-select-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormStrongPasswordFieldRoute =
  DocsComponentsFormStrongPasswordFieldRouteImport.update({
    id: '/docs/components/form-strong-password-field',
    path: '/docs/components/form-strong-password-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormTextFieldRoute =
  DocsComponentsFormTextFieldRouteImport.update({
    id: '/docs/components/form-text-field',
    path: '/docs/components/form-text-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormTextareaFieldRoute =
  DocsComponentsFormTextareaFieldRouteImport.update({
    id: '/docs/components/form-textarea-field',
    path: '/docs/components/form-textarea-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsFormTimeFieldRoute =
  DocsComponentsFormTimeFieldRouteImport.update({
    id: '/docs/components/form-time-field',
    path: '/docs/components/form-time-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsSidebarRoute = DocsComponentsSidebarRouteImport.update({
  id: '/docs/components/sidebar',
  path: '/docs/components/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSpinnerRoute = DocsComponentsSpinnerRouteImport.update({
  id: '/docs/components/spinner',
  path: '/docs/components/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsThemeProviderRoute =
  DocsComponentsThemeProviderRouteImport.update({
    id: '/docs/components/theme-provider',
    path: '/docs/components/theme-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsComponentsThemeToggleRoute =
  DocsComponentsThemeToggleRouteImport.update({
    id: '/docs/components/theme-toggle',
    path: '/docs/components/theme-toggle',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/blocks/admin-page': typeof DocsBlocksAdminPageRoute
  '/docs/blocks/sidebar-layout': typeof DocsBlocksSidebarLayoutRoute
  '/docs/components/app-sidebar': typeof DocsComponentsAppSidebarRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/data-table-cells': typeof DocsComponentsDataTableCellsRoute
  '/docs/components/data-table-view-options': typeof DocsComponentsDataTableViewOptionsRoute
  '/docs/components/form-checkbox-field': typeof DocsComponentsFormCheckboxFieldRoute
  '/docs/components/form-currency-field': typeof DocsComponentsFormCurrencyFieldRoute
  '/docs/components/form-date-field': typeof DocsComponentsFormDateFieldRoute
  '/docs/components/form-email-field': typeof DocsComponentsFormEmailFieldRoute
  '/docs/components/form-fields': typeof DocsComponentsFormFieldsRoute
  '/docs/components/form-number-field': typeof DocsComponentsFormNumberFieldRoute
  '/docs/components/form-password-field': typeof DocsComponentsFormPasswordFieldRoute
  '/docs/components/form-select-field': typeof DocsComponentsFormSelectFieldRoute
  '/docs/components/form-strong-password-field': typeof DocsComponentsFormStrongPasswordFieldRoute
  '/docs/components/form-text-field': typeof DocsComponentsFormTextFieldRoute
  '/docs/components/form-textarea-field': typeof DocsComponentsFormTextareaFieldRoute
  '/docs/components/form-time-field': typeof DocsComponentsFormTimeFieldRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/theme-provider': typeof DocsComponentsThemeProviderRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs': typeof DocsIndexRoute
  '/docs/blocks/admin-page': typeof DocsBlocksAdminPageRoute
  '/docs/blocks/sidebar-layout': typeof DocsBlocksSidebarLayoutRoute
  '/docs/components/app-sidebar': typeof DocsComponentsAppSidebarRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/data-table-cells': typeof DocsComponentsDataTableCellsRoute
  '/docs/components/data-table-view-options': typeof DocsComponentsDataTableViewOptionsRoute
  '/docs/components/form-checkbox-field': typeof DocsComponentsFormCheckboxFieldRoute
  '/docs/components/form-currency-field': typeof DocsComponentsFormCurrencyFieldRoute
  '/docs/components/form-date-field': typeof DocsComponentsFormDateFieldRoute
  '/docs/components/form-email-field': typeof DocsComponentsFormEmailFieldRoute
  '/docs/components/form-fields': typeof DocsComponentsFormFieldsRoute
  '/docs/components/form-number-field': typeof DocsComponentsFormNumberFieldRoute
  '/docs/components/form-password-field': typeof DocsComponentsFormPasswordFieldRoute
  '/docs/components/form-select-field': typeof DocsComponentsFormSelectFieldRoute
  '/docs/components/form-strong-password-field': typeof DocsComponentsFormStrongPasswordFieldRoute
  '/docs/components/form-text-field': typeof DocsComponentsFormTextFieldRoute
  '/docs/components/form-textarea-field': typeof DocsComponentsFormTextareaFieldRoute
  '/docs/components/form-time-field': typeof DocsComponentsFormTimeFieldRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/theme-provider': typeof DocsComponentsThemeProviderRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/components': typeof DocsComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/blocks/admin-page': typeof DocsBlocksAdminPageRoute
  '/docs/blocks/sidebar-layout': typeof DocsBlocksSidebarLayoutRoute
  '/docs/components/app-sidebar': typeof DocsComponentsAppSidebarRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
  '/docs/components/data-table-cells': typeof DocsComponentsDataTableCellsRoute
  '/docs/components/data-table-view-options': typeof DocsComponentsDataTableViewOptionsRoute
  '/docs/components/form-checkbox-field': typeof DocsComponentsFormCheckboxFieldRoute
  '/docs/components/form-currency-field': typeof DocsComponentsFormCurrencyFieldRoute
  '/docs/components/form-date-field': typeof DocsComponentsFormDateFieldRoute
  '/docs/components/form-email-field': typeof DocsComponentsFormEmailFieldRoute
  '/docs/components/form-fields': typeof DocsComponentsFormFieldsRoute
  '/docs/components/form-number-field': typeof DocsComponentsFormNumberFieldRoute
  '/docs/components/form-password-field': typeof DocsComponentsFormPasswordFieldRoute
  '/docs/components/form-select-field': typeof DocsComponentsFormSelectFieldRoute
  '/docs/components/form-strong-password-field': typeof DocsComponentsFormStrongPasswordFieldRoute
  '/docs/components/form-text-field': typeof DocsComponentsFormTextFieldRoute
  '/docs/components/form-textarea-field': typeof DocsComponentsFormTextareaFieldRoute
  '/docs/components/form-time-field': typeof DocsComponentsFormTimeFieldRoute
  '/docs/components/sidebar': typeof DocsComponentsSidebarRoute
  '/docs/components/spinner': typeof DocsComponentsSpinnerRoute
  '/docs/components/theme-provider': typeof DocsComponentsThemeProviderRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/'
    | '/docs/blocks/admin-page'
    | '/docs/blocks/sidebar-layout'
    | '/docs/components/app-sidebar'
    | '/docs/components/data-table'
    | '/docs/components/data-table-cells'
    | '/docs/components/data-table-view-options'
    | '/docs/components/form-checkbox-field'
    | '/docs/components/form-currency-field'
    | '/docs/components/form-date-field'
    | '/docs/components/form-email-field'
    | '/docs/components/form-fields'
    | '/docs/components/form-number-field'
    | '/docs/components/form-password-field'
    | '/docs/components/form-select-field'
    | '/docs/components/form-strong-password-field'
    | '/docs/components/form-text-field'
    | '/docs/components/form-textarea-field'
    | '/docs/components/form-time-field'
    | '/docs/components/sidebar'
    | '/docs/components/spinner'
    | '/docs/components/theme-provider'
    | '/docs/components/theme-toggle'
    | '/docs/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs'
    | '/docs/blocks/admin-page'
    | '/docs/blocks/sidebar-layout'
    | '/docs/components/app-sidebar'
    | '/docs/components/data-table'
    | '/docs/components/data-table-cells'
    | '/docs/components/data-table-view-options'
    | '/docs/components/form-checkbox-field'
    | '/docs/components/form-currency-field'
    | '/docs/components/form-date-field'
    | '/docs/components/form-email-field'
    | '/docs/components/form-fields'
    | '/docs/components/form-number-field'
    | '/docs/components/form-password-field'
    | '/docs/components/form-select-field'
    | '/docs/components/form-strong-password-field'
    | '/docs/components/form-text-field'
    | '/docs/components/form-textarea-field'
    | '/docs/components/form-time-field'
    | '/docs/components/sidebar'
    | '/docs/components/spinner'
    | '/docs/components/theme-provider'
    | '/docs/components/theme-toggle'
    | '/docs/components'
  id:
    | '__root__'
    | '/'
    | '/docs/installation'
    | '/docs/introduction'
    | '/docs/'
    | '/docs/blocks/admin-page'
    | '/docs/blocks/sidebar-layout'
    | '/docs/components/app-sidebar'
    | '/docs/components/data-table'
    | '/docs/components/data-table-cells'
    | '/docs/components/data-table-view-options'
    | '/docs/components/form-checkbox-field'
    | '/docs/components/form-currency-field'
    | '/docs/components/form-date-field'
    | '/docs/components/form-email-field'
    | '/docs/components/form-fields'
    | '/docs/components/form-number-field'
    | '/docs/components/form-password-field'
    | '/docs/components/form-select-field'
    | '/docs/components/form-strong-password-field'
    | '/docs/components/form-text-field'
    | '/docs/components/form-textarea-field'
    | '/docs/components/form-time-field'
    | '/docs/components/sidebar'
    | '/docs/components/spinner'
    | '/docs/components/theme-provider'
    | '/docs/components/theme-toggle'
    | '/docs/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsIntroductionRoute: typeof DocsIntroductionRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsBlocksAdminPageRoute: typeof DocsBlocksAdminPageRoute
  DocsBlocksSidebarLayoutRoute: typeof DocsBlocksSidebarLayoutRoute
  DocsComponentsAppSidebarRoute: typeof DocsComponentsAppSidebarRoute
  DocsComponentsDataTableRoute: typeof DocsComponentsDataTableRoute
  DocsComponentsDataTableCellsRoute: typeof DocsComponentsDataTableCellsRoute
  DocsComponentsDataTableViewOptionsRoute: typeof DocsComponentsDataTableViewOptionsRoute
  DocsComponentsFormCheckboxFieldRoute: typeof DocsComponentsFormCheckboxFieldRoute
  DocsComponentsFormCurrencyFieldRoute: typeof DocsComponentsFormCurrencyFieldRoute
  DocsComponentsFormDateFieldRoute: typeof DocsComponentsFormDateFieldRoute
  DocsComponentsFormEmailFieldRoute: typeof DocsComponentsFormEmailFieldRoute
  DocsComponentsFormFieldsRoute: typeof DocsComponentsFormFieldsRoute
  DocsComponentsFormNumberFieldRoute: typeof DocsComponentsFormNumberFieldRoute
  DocsComponentsFormPasswordFieldRoute: typeof DocsComponentsFormPasswordFieldRoute
  DocsComponentsFormSelectFieldRoute: typeof DocsComponentsFormSelectFieldRoute
  DocsComponentsFormStrongPasswordFieldRoute: typeof DocsComponentsFormStrongPasswordFieldRoute
  DocsComponentsFormTextFieldRoute: typeof DocsComponentsFormTextFieldRoute
  DocsComponentsFormTextareaFieldRoute: typeof DocsComponentsFormTextareaFieldRoute
  DocsComponentsFormTimeFieldRoute: typeof DocsComponentsFormTimeFieldRoute
  DocsComponentsSidebarRoute: typeof DocsComponentsSidebarRoute
  DocsComponentsSpinnerRoute: typeof DocsComponentsSpinnerRoute
  DocsComponentsThemeProviderRoute: typeof DocsComponentsThemeProviderRoute
  DocsComponentsThemeToggleRoute: typeof DocsComponentsThemeToggleRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/introduction': {
      id: '/docs/introduction'
      path: '/docs/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/blocks/admin-page': {
      id: '/docs/blocks/admin-page'
      path: '/docs/blocks/admin-page'
      fullPath: '/docs/blocks/admin-page'
      preLoaderRoute: typeof DocsBlocksAdminPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/blocks/sidebar-layout': {
      id: '/docs/blocks/sidebar-layout'
      path: '/docs/blocks/sidebar-layout'
      fullPath: '/docs/blocks/sidebar-layout'
      preLoaderRoute: typeof DocsBlocksSidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/docs/components'
      fullPath: '/docs/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/app-sidebar': {
      id: '/docs/components/app-sidebar'
      path: '/docs/components/app-sidebar'
      fullPath: '/docs/components/app-sidebar'
      preLoaderRoute: typeof DocsComponentsAppSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/data-table': {
      id: '/docs/components/data-table'
      path: '/docs/components/data-table'
      fullPath: '/docs/components/data-table'
      preLoaderRoute: typeof DocsComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/data-table-cells': {
      id: '/docs/components/data-table-cells'
      path: '/docs/components/data-table-cells'
      fullPath: '/docs/components/data-table-cells'
      preLoaderRoute: typeof DocsComponentsDataTableCellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/data-table-view-options': {
      id: '/docs/components/data-table-view-options'
      path: '/docs/components/data-table-view-options'
      fullPath: '/docs/components/data-table-view-options'
      preLoaderRoute: typeof DocsComponentsDataTableViewOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-checkbox-field': {
      id: '/docs/components/form-checkbox-field'
      path: '/docs/components/form-checkbox-field'
      fullPath: '/docs/components/form-checkbox-field'
      preLoaderRoute: typeof DocsComponentsFormCheckboxFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-currency-field': {
      id: '/docs/components/form-currency-field'
      path: '/docs/components/form-currency-field'
      fullPath: '/docs/components/form-currency-field'
      preLoaderRoute: typeof DocsComponentsFormCurrencyFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-date-field': {
      id: '/docs/components/form-date-field'
      path: '/docs/components/form-date-field'
      fullPath: '/docs/components/form-date-field'
      preLoaderRoute: typeof DocsComponentsFormDateFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-email-field': {
      id: '/docs/components/form-email-field'
      path: '/docs/components/form-email-field'
      fullPath: '/docs/components/form-email-field'
      preLoaderRoute: typeof DocsComponentsFormEmailFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-fields': {
      id: '/docs/components/form-fields'
      path: '/docs/components/form-fields'
      fullPath: '/docs/components/form-fields'
      preLoaderRoute: typeof DocsComponentsFormFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-number-field': {
      id: '/docs/components/form-number-field'
      path: '/docs/components/form-number-field'
      fullPath: '/docs/components/form-number-field'
      preLoaderRoute: typeof DocsComponentsFormNumberFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-password-field': {
      id: '/docs/components/form-password-field'
      path: '/docs/components/form-password-field'
      fullPath: '/docs/components/form-password-field'
      preLoaderRoute: typeof DocsComponentsFormPasswordFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-select-field': {
      id: '/docs/components/form-select-field'
      path: '/docs/components/form-select-field'
      fullPath: '/docs/components/form-select-field'
      preLoaderRoute: typeof DocsComponentsFormSelectFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-strong-password-field': {
      id: '/docs/components/form-strong-password-field'
      path: '/docs/components/form-strong-password-field'
      fullPath: '/docs/components/form-strong-password-field'
      preLoaderRoute: typeof DocsComponentsFormStrongPasswordFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-text-field': {
      id: '/docs/components/form-text-field'
      path: '/docs/components/form-text-field'
      fullPath: '/docs/components/form-text-field'
      preLoaderRoute: typeof DocsComponentsFormTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-textarea-field': {
      id: '/docs/components/form-textarea-field'
      path: '/docs/components/form-textarea-field'
      fullPath: '/docs/components/form-textarea-field'
      preLoaderRoute: typeof DocsComponentsFormTextareaFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/form-time-field': {
      id: '/docs/components/form-time-field'
      path: '/docs/components/form-time-field'
      fullPath: '/docs/components/form-time-field'
      preLoaderRoute: typeof DocsComponentsFormTimeFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/sidebar': {
      id: '/docs/components/sidebar'
      path: '/docs/components/sidebar'
      fullPath: '/docs/components/sidebar'
      preLoaderRoute: typeof DocsComponentsSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/spinner': {
      id: '/docs/components/spinner'
      path: '/docs/components/spinner'
      fullPath: '/docs/components/spinner'
      preLoaderRoute: typeof DocsComponentsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/theme-provider': {
      id: '/docs/components/theme-provider'
      path: '/docs/components/theme-provider'
      fullPath: '/docs/components/theme-provider'
      preLoaderRoute: typeof DocsComponentsThemeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/components/theme-toggle': {
      id: '/docs/components/theme-toggle'
      path: '/docs/components/theme-toggle'
      fullPath: '/docs/components/theme-toggle'
      preLoaderRoute: typeof DocsComponentsThemeToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsIntroductionRoute: DocsIntroductionRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsBlocksAdminPageRoute: DocsBlocksAdminPageRoute,
  DocsBlocksSidebarLayoutRoute: DocsBlocksSidebarLayoutRoute,
  DocsComponentsAppSidebarRoute: DocsComponentsAppSidebarRoute,
  DocsComponentsDataTableRoute: DocsComponentsDataTableRoute,
  DocsComponentsDataTableCellsRoute: DocsComponentsDataTableCellsRoute,
  DocsComponentsDataTableViewOptionsRoute:
    DocsComponentsDataTableViewOptionsRoute,
  DocsComponentsFormCheckboxFieldRoute: DocsComponentsFormCheckboxFieldRoute,
  DocsComponentsFormCurrencyFieldRoute: DocsComponentsFormCurrencyFieldRoute,
  DocsComponentsFormDateFieldRoute: DocsComponentsFormDateFieldRoute,
  DocsComponentsFormEmailFieldRoute: DocsComponentsFormEmailFieldRoute,
  DocsComponentsFormFieldsRoute: DocsComponentsFormFieldsRoute,
  DocsComponentsFormNumberFieldRoute: DocsComponentsFormNumberFieldRoute,
  DocsComponentsFormPasswordFieldRoute: DocsComponentsFormPasswordFieldRoute,
  DocsComponentsFormSelectFieldRoute: DocsComponentsFormSelectFieldRoute,
  DocsComponentsFormStrongPasswordFieldRoute:
    DocsComponentsFormStrongPasswordFieldRoute,
  DocsComponentsFormTextFieldRoute: DocsComponentsFormTextFieldRoute,
  DocsComponentsFormTextareaFieldRoute: DocsComponentsFormTextareaFieldRoute,
  DocsComponentsFormTimeFieldRoute: DocsComponentsFormTimeFieldRoute,
  DocsComponentsSidebarRoute: DocsComponentsSidebarRoute,
  DocsComponentsSpinnerRoute: DocsComponentsSpinnerRoute,
  DocsComponentsThemeProviderRoute: DocsComponentsThemeProviderRoute,
  DocsComponentsThemeToggleRoute: DocsComponentsThemeToggleRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
